---
- name: VM
  hosts: all
  become: yes
  become_user: root
  collections:
    - ansible.posix
    - community.crypto

  pre_tasks:
    - name: update OS
      yum:
        name: "*"
        state: latest

    - name: reboot from update
      reboot:
        reboot_timeout: 210

    - name: install needed packages
      yum:
        name:
          - podman
          - dnf-automatic

    - name: enable yum-cron updates
      lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: "apply_updates = no"
        line: apply_updates = yes

  tasks:
    - include_tasks: tasks/nginx.yml
    - include_tasks: tasks/postgresql.yml

  post_tasks:
    - name: enable services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - dnf-automatic.timer
        - podman
